### ISSUE TITLE
Cannot find module ./query

### ISSUE THREAD

**Issue by Ayeven** [marceloclp/calpheonjs#2]
`[2020-11-29 16:17:35]: CMD [CMD] Bot Owner Ayeven (273097175452614666) ran command calpheon
[2020-11-29 16:17:35]: ERROR Unhandled rejection: Error: Cannot find module './query'
Require stack:
- /home/runner/ayevenbot/node_modules/calpheonjs/dist/index.js
- /home/runner/ayevenbot/commands/calpheon.js
- /home/runner/ayevenbot/modules/functions.js
- /home/runner/ayevenbot/index.js 
Error: Cannot find module './query'
Require stack:
- /home/runner/ayevenbot/node_modules/calpheonjs/dist/index.js
- /home/runner/ayevenbot/commands/calpheon.js
- /home/runner/ayevenbot/modules/functions.js
- /home/runner/ayevenbot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/ayevenbot/node_modules/calpheonjs/dist/index.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/ayevenbot/node_modules/calpheonjs/dist/index.js',
    '/home/runner/ayevenbot/commands/calpheon.js',
    '/home/runner/ayevenbot/modules/functions.js',
    '/home/runner/ayevenbot/index.js'
  ]
}`
I'm not sure if this only happen if you using it on repl.it. I have not tested on development platform/own pc. I have not tried to manually upload the necessary folder to my repl.it project either. I have tried the older bdo-scrapper and it working on my repl.it

**Comment by GnubiBORED** [comment]
did u solve it?

**Comment by jojo5528** [comment]
+rep, i have this issue too.
 this is my log (using laravel-mix)

> × Mix
Compiled with some errors in 321.57ms
ERROR in ./node_modules/calpheonjs/dist/index.js 14:13-31
Module not found: Error: Can't resolve './query' in 'E:\ProjectWWW\lm_bdovue\node_modules\calpheonjs\dist'
ERROR in ./node_modules/calpheonjs/dist/index.js 15:13-33
Module not found: Error: Can't resolve './scraper' in 'E:\ProjectWWW\lm_bdovue\node_modules\calpheonjs\dist'
ERROR in ./node_modules/calpheonjs/dist/index.js 16:13-50
Module not found: Error: Can't resolve './shared/typings/app/enums' in 'E:\ProjectWWW\lm_bdovue\node_modules\calpheonjs\dist'
ERROR in ./node_modules/calpheonjs/dist/index.js 17:12-43
Module not found: Error: Can't resolve './shared/typings/app' in 'E:\ProjectWWW\lm_bdovue\node_modules\calpheonjs\dist'
webpack compiled with 4 errors

**Comment by marceloclp** [comment]
Sorry, I haven't checked GitHub's notifications in a while. This is due to the package declaration files not being compiled properly. This is my fault and I don't think there is much you guys can do.

I will be releasing the next version on the following week, so I won't spend time fixing compilation errors on the current one. But feel free to open a PR and I will merge it.

**Comment by alancuriel** [comment]
#6
